# Generated by Django 2.0.4 on 2018-04-03 05:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='input_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='input_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('number', 'number'), ('password', 'password'), ('email', 'email'), ('check', 'checkbox'), ('date', 'date'), ('datetime-local', 'datetime-local'), ('url', 'url')], max_length=128, null=True),
        ),
    ]
