# Generated by Django 2.0.4 on 2018-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180403_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
