# Generated by Django 2.0.4 on 2018-04-04 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180403_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='posts.Category'),
        ),
    ]
