# Generated by Django 2.0.4 on 2018-04-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180404_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='input_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('number', 'number'), ('checkbox', 'checkbox'), ('date', 'date')], max_length=128, null=True),
        ),
    ]
